# Generated by Django 4.2.7 on 2025-10-20 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('reminder_date', models.DateTimeField(verbose_name='Data do Lembrete')),
                ('frequency', models.CharField(choices=[('once', 'Uma vez'), ('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='once', max_length=10, verbose_name='Frequência')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Último Envio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('budget_warning', 'Alerta de Orçamento (80%)'), ('budget_exceeded', 'Orçamento Excedido'), ('goal_achieved', 'Meta Atingida'), ('goal_overdue', 'Meta Atrasada'), ('reminder', 'Lembrete')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
