# Generated by Django 4.2.7 on 2025-10-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('near_limit', 'Próximo do Limite (80%)'), ('over_budget', 'Orçamento Excedido'), ('projection_warning', 'Projeção de Excesso'), ('trend_warning', 'Tendência Preocupante')], max_length=20)),
                ('alert_level', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=10)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.budget')),
            ],
            options={
                'verbose_name': 'Alerta de Orçamento',
                'verbose_name_plural': 'Alertas de Orçamento',
                'ordering': ['-created_at'],
                'unique_together': {('budget', 'alert_type', 'is_active')},
            },
        ),
    ]
