global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@nossagrana.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    email_configs:
      - to: 'admin@nossagrana.com'
        subject: '[NOSSA GRANA] Alerta: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alerta: {{ .Annotations.summary }}
          Descrição: {{ .Annotations.description }}
          Severidade: {{ .Labels.severity }}
          Instância: {{ .Labels.instance }}
          Horário: {{ .StartsAt }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']