# Generated by Django 4.2.7 on 2025-10-20 15:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Meta')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Alvo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Atual')),
                ('target_date', models.DateField(verbose_name='Data Objetivo')),
                ('achieved', models.BooleanField(default=False, verbose_name='Meta Atingida')),
                ('achieved_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conquista')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Meta de Poupança',
                'verbose_name_plural': 'Metas de Poupança',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da Contribuição')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.goal', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Contribuição para Meta',
                'verbose_name_plural': 'Contribuições para Metas',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
