# Generated by Django 4.2.7 on 2025-10-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
    ]
