# Generated by Django 4.2.7 on 2025-10-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_accounts.account', verbose_name='Conta Bancária'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_accounts.creditcard', verbose_name='Cartão de Crédito'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='financial_accounts.account', verbose_name='Conta Origem'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='financial_accounts.account', verbose_name='Conta Destino'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('transfer', 'Transferência')], max_length=10, verbose_name='Tipo'),
        ),
    ]
