# Generated by Django 4.2.7 on 2025-10-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20251021_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
